S2ale/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import handler404, handler500

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Service.urls')),
    path('Lessons/', include('Lessons.urls')),
    path('account/', include('Accounts.urls')),
    path('accounts/', include('allauth.urls')),

    # url(r'^media/(?P<path>.*)$', serve,{'document_root':       settings.MEDIA_ROOT}),
    # url(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}),
]

handler404 = 'Accounts.views.error_404'
handler500 = 'Accounts.views.error_500'

Service/urls.py
from django.urls import path, re_path
from . import views


app_name = 'Service'


urlpatterns = [
    path('', views.landinpage, name='landingpage'),
    path('S2ale/', views.home, name='Home'),
    path('<str:pk>/', views.home, name='Home'),

    path('Terms', views.website_terms, name='Policy'),

    path('<str:pk>/Categorie/Design', views.design, name='Design'),
    path('Categorie/Design', views.design, name='Design'),

    path("<str:pk>/Categorie/Coding", views.code, name='Coding'),
    path('Categorie/Coding', views.code, name='Coding'),


    path('<str:pk>/Categorie/Language', views.language, name='Language'),
    path('Categorie/Language', views.language, name='Language'),
]

Service/models.py
from django.db import models
# Create your models here.

Service/views.py
from django.shortcuts import render, redirect, get_object_or_404
from Accounts.models import User, UserSubscription
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from allauth.socialaccount.models import SocialAccount
import requests


def landinpage(request):
    return render(request, 'service/Home/Home.html')


@login_required()
def home(request, pk=None):
    user = request.user
    if user.is_authenticated and pk is not None:
        authenticated = User.objects.filter(uids=pk)
        # Google Avatar
        if SocialAccount.objects.filter(user=user, provider='google'):
            avatar = SocialAccount.objects.get(
                extra_data__contains=user.email).extra_data['picture']
        # Github Avatar
        elif SocialAccount.objects.filter(user=user, provider='github'):
            avatar = SocialAccount.objects.get(
                extra_data__contains=user.email).extra_data['avatar_url']
        else:

            return render(request, 'service/Home/Feed.html', context={'username': user.username, 'user': user})

        return render(request, 'service/Home/Feed.html', context={'username': user.username, 'user': user, 'Avatar': avatar})

    return render(request, 'service/Home/Feed.html')


@ login_required(login_url='Accounts:Login')
def design(request, pk=None):
    user = request.user
    if user.is_authenticated and pk is not None:
        authenticated = User.objects.filter(uids=pk)

    return render(request, 'service/Categories/Design.html', context={'user': user})


@ login_required(login_url='Accounts:Login')
def code(request, pk=None):
    user = request.user
    if user.is_authenticated and pk is not None:
        authenticated = User.objects.filter(uids=pk)
    return render(request, 'service/Categories/Coding.html', context={'user': user})


@ login_required(login_url='Accounts:Login')
def language(request, pk=None):
    user = request.user
    if user.is_authenticated and pk is not None:
        authenticated = User.objects.filter(uids=pk)

    return render(request, 'service/Categories/Language.html', context={'user': request.user})


@ login_required(login_url='Accounts:Login')
def website_terms(request):
    user = request.user
    if user.is_authenticated and pk is not None:
        authenticated = User.objects.filter(uids=pk)

    return render(request, 'service/Home/Policy.html', context={'pk': request.user.username})

Service/templates/Base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  {% block head %}
    
  {% endblock head %}
  <link rel="stylesheet" type="text/css" href="{% static '/css/Base.css' %}" />

  <link rel="stylesheet" type="text/css" href="{% static '/css/Barba.css' %}" />

  <link rel="icon" type="image/x-icon" href="{% static '/images/Logo/Faveicon.png' %}">
  <!--<link rel="stylesheet" href="https://unpkg.com/aos@next/dist/aos.css" />-->
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
  <script src="https://unpkg.com/scrollreveal"></script>




</head>
<body data-barba="wrapper">
  <div class="load-container">
    <div class="loading-screen"></div>
  </div>

  {% block Home %}

  {% endblock Home %}

  <script src="https://code.iconify.design/iconify-icon/1.0.1/iconify-icon.min.js"></script>

  <!-- AOS animation -->
  <script src="https://unpkg.com/aos@next/dist/aos.js"></script>
  <script>
    AOS.init();
  </script>
  <!-- To Show the rest of page while click the scroll down button -->
  <script>function Showthepage() {
    var categories = document.getElementById("Categories");
    categories.style.display = "block";
    var vote = document.getElementById("Vote");
    vote.style.display = "block";
    var footer = document.getElementById("footer");
    footer.style.display = "block";  // <-- Set it to block
  }</script>

  
  {% if user.is_authenticated %}
  <script>
    window.onload=Showthepage()
  </script>
  {% endif %}

  <!-- Barba -->
  <script src="{% static '/js/Barba.js' %}"></script>

  <script src="https://unpkg.com/@barba/core"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/gsap/3.11.3/gsap.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.1/jquery.min.js"></script>

</body>
</html>

Service/templates/Categories.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>{% block title %}{% endblock title %}</title>
  <!-- Faveicon -->
  <link rel="icon" type="image/x-icon" href="{% static '/images/Logo/Faveicon.png' %}">
  <link rel="stylesheet" type="text/css" href="{% static '/css/Categories/Categories.css' %}" />
  <!-- Animation aos link -->
  <link rel="stylesheet" href="https://unpkg.com/aos@next/dist/aos.css" />

  <!-- Swiper -->
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/swiper@8/swiper-bundle.min.css"/>

    <!-- Figma icons -->
  <script src="https://code.iconify.design/iconify-icon/1.0.1/iconify-icon.min.js"></script>
  {% block head %}
    
  {% endblock head %}
</head>
<body>
  <!-- Previes page button -->
  <a class="Previous" href="{% url 'Service:Home' user.uids %}#Categories">
    <iconify-icon icon="bi:arrow-left-circle-fill" width='70' height='50'></iconify-icon>
  </a>

  <!-- Categories -->
  <section class="Categories swiper" id="Categories">
    <div class="categories__ swiper-wrapper">
      {% block categories %}
        
      {% endblock categories %}
    </div>
  <div class="swiper-button-next"></div>
  <div class="swiper-button-prev"></div>
  <div class="swiper-pagination"></div>
  </section>

  <!-- Swiper JS -->
  <script src="https://cdn.jsdelivr.net/npm/swiper/swiper-bundle.min.js"></script>

   <!-- AOS animation -->
   <script src="https://unpkg.com/aos@next/dist/aos.js"></script>

   <script src="https://unpkg.com/aos@next/dist/aos.js"></script>
   <script>
     AOS.init();
   </script>

</body>
<!-- Grid lines -->
{% block grid %}
    
{% endblock grid %}

{% block swip %}
  
{% endblock swip %}


</html>