Lessons/urls.py
from django.urls import path, re_path
from . import views


app_name = 'Lessons'

urlpatterns = [
    #------------------ Illustrator

    path('illustrator', views.illustrator, name='illustrator'),
    path('<str:pk>/illustrator', views.illustrator, name='illustrator'),

    #------------------ Photoshop

    path('photoshop', views.photoshop, name='photoshop'),
    path('<str:pk>/photoshop', views.photoshop, name='photoshop'),

    #------------------ Premier-pro

    path('premier-pro', views.premier_pro, name='premier-pro'),
    path('<str:pk>/premier-pro', views.premier_pro, name='premier-pro'),

    # ------------------ 3ds Max

    path('3ds-max', views.tds_max, name='3ds-max'),
    path('<str:pk>/3ds-max', views.tds_max, name='3ds-max'),

    # -------------- Code Categorie ---------------------------
    path('coding', views.code, name='coding'),
    path('<str:pk>/coding', views.code, name='coding'),

    path('algorithms', views.algo, name='algorithms'),
    path('<str:pk>/algorithms', views.algo, name='algorithms'),

    path('math-informatique', views.math, name='math-informatique'),
    path('<str:pk>/math-informatique', views.math, name='math-informatique'),


    # -------------- Language Categorie -----------------
    path('french', views.french, name='french'),
    path('<str:pk>/french', views.french, name='french'),

    path('english', views.english, name='english'),
    path('<str:pk>/english', views.english, name='english'),

]

S2ale/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import handler404, handler500

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Service.urls')),
    path('Lessons/', include('Lessons.urls')),
    path('account/', include('Accounts.urls')),
    path('accounts/', include('allauth.urls')),

    # url(r'^media/(?P<path>.*)$', serve,{'document_root':       settings.MEDIA_ROOT}),
    # url(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}),
]

handler404 = 'Accounts.views.error_404'
handler500 = 'Accounts.views.error_500'

Service/urls.py
from django.urls import path, re_path
from . import views


app_name = 'Service'


urlpatterns = [
    path('', views.landinpage, name='landingpage'),
    path('S2ale/', views.home, name='Home'),
    path('<str:pk>/', views.home, name='Home'),

    path('Terms', views.website_terms, name='Policy'),

    path('<str:pk>/Categorie/Design', views.design, name='Design'),
    path('Categorie/Design', views.design, name='Design'),

    path("<str:pk>/Categorie/Coding", views.code, name='Coding'),
    path('Categorie/Coding', views.code, name='Coding'),


    path('<str:pk>/Categorie/Language', views.language, name='Language'),
    path('Categorie/Language', views.language, name='Language'),
]

Service/models.py
from django.db import models
# Create your models here.

Service/views.py
from django.shortcuts import render, redirect, get_object_or_404
from Accounts.models import User, UserSubscription
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from allauth.socialaccount.models import SocialAccount
import requests


def landinpage(request):
    return render(request, 'service/Home/Home.html')


@login_required()
def home(request, pk=None):
    user = request.user
    if user.is_authenticated and pk is not None:
        authenticated = User.objects.filter(uids=pk)
        # Google Avatar
        if SocialAccount.objects.filter(user=user, provider='google'):
            avatar = SocialAccount.objects.get(
                extra_data__contains=user.email).extra_data['picture']
        # Github Avatar
        elif SocialAccount.objects.filter(user=user, provider='github'):
            avatar = SocialAccount.objects.get(
                extra_data__contains=user.email).extra_data['avatar_url']
        else:

            return render(request, 'service/Home/Feed.html', context={'username': user.username, 'user': user})

        return render(request, 'service/Home/Feed.html', context={'username': user.username, 'user': user, 'Avatar': avatar})

    return render(request, 'service/Home/Feed.html')


@ login_required(login_url='Accounts:Login')
def design(request, pk=None):
    user = request.user
    if user.is_authenticated and pk is not None:
        authenticated = User.objects.filter(uids=pk)

    return render(request, 'service/Categories/Design.html', context={'user': user})


@ login_required(login_url='Accounts:Login')
def code(request, pk=None):
    user = request.user
    if user.is_authenticated and pk is not None:
        authenticated = User.objects.filter(uids=pk)
    return render(request, 'service/Categories/Coding.html', context={'user': user})


@ login_required(login_url='Accounts:Login')
def language(request, pk=None):
    user = request.user
    if user.is_authenticated and pk is not None:
        authenticated = User.objects.filter(uids=pk)

    return render(request, 'service/Categories/Language.html', context={'user': request.user})


@ login_required(login_url='Accounts:Login')
def website_terms(request):
    user = request.user
    if user.is_authenticated and pk is not None:
        authenticated = User.objects.filter(uids=pk)

    return render(request, 'service/Home/Policy.html', context={'pk': request.user.username})

Service/templates/service/Categories/Coding.html
{% extends 'Categories.html' %}
{% load static %}

{% block title %}
    Coding  
{% endblock title %}

{% block head %}
    <link rel="stylesheet" type="text/css" href="{% static '/css/Categories/Coding.css' %}" />  
{% endblock head %}


{% block categories %}
    {% if user.is_authenticated %}
    <a data-aos="flip-right" href="{% url 'Lessons:math-informatique' user.uids %}#Cards" class="Cards swiper-slide" id="Code-Math">
      <div class="text">
        <h1>There no such<br>
          thing as boring mathematics</h1>
        <h4>Build your brand, make a meme, or explore your inner artist</h4>
      </div>
    </a>
    {% else %}
    <a data-aos="flip-right" href="{% url 'Lessons:math-informatique' user.uids %}#Cards" class="Cards swiper-slide" id="Code-Math">
      <algodiv class="text">
        <h1>There no such<br>
          thing as boring mathematics</h1>
        <h4>Build your brand, make a meme, or explore your inner artist</h4>
      </div>
    </a>
    {% endif %}

    {% if user.is_authenticated %}
    <a data-aos="flip-left" href="{% url 'Lessons:algorithms' user.uids %}#Cards" class="Cards swiper-slide" id="Code-Algo">
      <div class="text">
        <h1>Algorithms for<br>learning algorithms</h1>
        <h4>learn different types of data structures and algorithms and their implementations </h4>
      </div>
    </a>
    {% else %}
    <a data-aos="flip-left" href="{% url 'Lessons:algorithms' user.uids %}#Cards" class="Cards swiper-slide" id="Code-Algo">
      <div class="text">
        <h1>Algorithms for<br>learning algorithms</h1>
        <h4>learn different types of data structures and algorithms and their implementations </h4>
      </div>
    </a>
    {% endif %}

    {% if user.is_authenticated %}
    <a data-aos="flip-right" href="{% url 'Lessons:coding' user.uids %}#Cards" class="Cards swiper-slide" id="Code">
      <div class="text">
        <h1>For every student,
          every classroom.
          Real results</h1>
        <h4>Our mission: to help people learn to code </h4>
      </div>
    </a>
    {% else %}
    <a data-aos="flip-right" href="{% url 'Lessons:coding' user.uids %}#Cards" class="Cards swiper-slide" id="Code">
      <div class="text">
        <h1>For every student,every classroom.
          Real results</h1>
        <h4>Our mission: to help people learn to code </h4>
      </div>
    </a>
    {% endif %}
{% endblock categories %}

{% block grid %}

<style>
  .Categories .categories__{
    display: grid;
    grid-template-columns: repeat(3, auto);  
  }
</style>

{% endblock grid %}

{% block swip %}
<script>
  var swiper = new Swiper(".Categories", {
    breakpoints: {
      421:{
        slidesPerView: 1,
      },
      520: {
        slidesPerView: 2,
      },
      768: {
        slidesPerView: 2,
      },
      1024: {
        slidesPerView: 3,
      },
    },
    pagination: {
      el: ".swiper-pagination",
      clickable: true,
    },
    navigation: {
      nextEl: ".swiper-button-next",
      prevEl: ".swiper-button-prev",
    },
  });
</script>
{% endblock swip %}

Service/templates/service/Categories/Design.html
{% extends "Categories.html" %}
{% load static %}

{% block title %}
    Design  
{% endblock title %}

{% block head %}
    <link rel="stylesheet" type="text/css" href="{% static '/css/Categories/Design.css' %}" />  
{% endblock head %}

{% block categories %}

    
    {% if user.is_authenticated %}
    <a data-aos="flip-left" data-aos-delay="50" href="{% url 'Lessons:photoshop' user.uids %}#Cards" class="Cards swiper-slide" id="Photoshop">
      <div class="text">
        <h1>Go from inspiration<br>to creation faster</h1>
        <h4>Build your brand, make a meme, or explore   your inner artist.</h4>
      </div>
    </a>
    {% else %}
    <a data-aos="flip-left" data-aos-delay="50" href="{% url 'Lessons:photoshop' %}#Cards" class="Cards swiper-slide" id="Photoshop">
    {% endif %}
    
    {% if user.is_authenticated %}
    <a data-aos="flip-right" data-aos-delay="100" href="{% url 'Lessons:illustrator' user.uids %}#Cards" class="Cards swiper-slide" id="Illustrator">
      <div class="text">
        <h1>Master your language with lessons</h1>
        <h4>Learning to Code Shouldn't Be Painful. Start  Your Coding Journey.</h4>
      </div>
    </a>
    {% else %}
    <a data-aos="flip-right" data-aos-delay="100" href="{% url 'Lessons:illustrator' %}#Cards" class="Cards swiper-slide" id="Illustrator">
    </a>
    {% endif %}
    
    {% if user.is_authenticated %}
    <a data-aos="flip-left" data-aos-delay="150" href="{% url 'Lessons:premier-pro' user.uids %}#Cards" class="Cards swiper-slide" id="Premier-pro">
      <div class="text">
        <h1>Learn how to speak, in the job market</h1>
        <h4>Speak in the language of bagettes and also  in the Harry Potter’s language.</h4>
      </div>
    </a>
    {% else %}
    <a data-aos="flip-left" data-aos-delay="150" href="{% url 'Lessons:premier-pro' %}#Cards" class="Cards swiper-slide" id="Premier-pro">
    </a>
    {% endif %}
    
    {% if user.is_authenticated %}
    <a data-aos="flip-right" data-aos-delay="200" href="{% url 'Lessons:3ds-max' user.uids %}#Cards" class="Cards swiper-slide" id="Tds-max">
      <div class="text">
        <h1>Learn how to speak, in the job market</h1>
        <h4>Speak in the language of bagettes and also  in the Harry Potter’s language.</h4>
      </div>
    </a>
    {% else %}
    <a data-aos="flip-right" data-aos-delay="200" href="{% url 'Lessons:3ds-max' %}#Cards" class="Cards swiper-slide" id="Tds-max">
    </a>
    {% endif %}

{% endblock categories %}

{% block grid %}

<style>
  .Categories .categories__{
    display: grid;
    grid-template-columns: repeat(4, auto);  
  }
</style>

{% endblock grid %}


{% block swip %}
<script>
  var swiper = new Swiper(".Categories", {
    breakpoints: {
      421:{
        slidesPerView: 1,
      },
      520: {
        slidesPerView: 2,
      },
      768: {
        slidesPerView: 2,
      },
      1024: {
        slidesPerView: 3,
      },
    },
    pagination: {
      el: ".swiper-pagination",
      clickable: true,
    },
    navigation: {
      nextEl: ".swiper-button-next",
      prevEl: ".swiper-button-prev",
    },
  });
</script>
{% endblock swip %}

Service/templates/service/Categories/Language.html
{% extends "Categories.html" %}
{% load static %}

{% block title %}
  Language  
{% endblock title %}

{% block head %}
  <link rel="stylesheet" type="text/css" href="{% static '/css/Categories/Language.css' %}" />
{% endblock head %}

{% block categories %}
    {% if user.is_authenticated %}
    <a data-aos="flip-left" href="{% url 'Lessons:english' user.uids %}#Cards" class="Cards swiper-slide" id="English">
      <div class="text">
        <h1>There no such<br>
          thing as boring mathematics</h1>
        <h4>Build your brand, make a meme, or explore your inner artist</h4>
      </div>
    </a>
    {% else %}
    <a data-aos="flip-left" href="{% url 'Lessons:english' user.uids %}#Cards" class="Cards swiper-slide" id="English">
      <div class="text">
        <h1>There no such<br>
          thing as boring mathematics</h1>
        <h4>Build your brand, make a meme, or explore your inner artist</h4>
      </div>
    </a>

    {% endif %}
    {% if user.is_authenticated %}
    <a data-aos="flip-right" href="{% url 'Lessons:french' user.uids %}#Cards" class="Cards swiper-slide" id="French">
      <div class="text">
        <h1>There no such 
          thing as boring mathematics</h1>
        <h4>Build your brand, make a meme, or explore your inner artist.</h4>
      </div>
    </a>
    {% else %}
    <a data-aos="flip-right" href="{% url 'Lessons:french' user.uids %}#Cards" class="Cards swiper-slide" id="French">
      <div class="text">
        <h1>There no such 
          thing as boring mathematics</h1>
        <h4>Build your brand, make a meme, or explore your inner artist.</h4>
      </div>
    </a>
    {% endif %}
{% endblock categories %}

{% block grid %}

<style>
  .Categories .categories__{
    display: grid;
    grid-template-columns: repeat(2, 1fr);  
  }
</style>

{% endblock grid %}

{% block swip %}
<script>
  var swiper = new Swiper(".Categories", {

    breakpoints: {
      421:{
        slidesPerView: 1,
      },
      520: {
        slidesPerView: 1,
      },
      768: {
        slidesPerView: 1,
      },
      1024: {
        slidesPerView: 2,
      },
    },
    pagination: {
      el: ".swiper-pagination",
      clickable: true,
    },
    navigation: {
      nextEl: ".swiper-button-next",
      prevEl: ".swiper-button-prev",
    },
  });
</script>
{% endblock swip %}